name: skillcraft_www
services:
  skillcraft_www:
    build:
      context: .
      dockerfile: Dockerfile
    image: skillcraft_www
    container_name: SkillCraft_www
    restart: unless-stopped
    ports:
      - 18088:80
